export FOURKEYS_PROJECT=${PARENT_PROJECT}
export FOURKEYS_REGION=${FOURKEYS_REGION}
export BILLING_ACCOUNT=${BILLING_ACCOUNT}
export PARENT_PROJECT=${PARENT_PROJECT}
export PARENT_FOLDER=${PARENT_FOLDER}
export GOOGLE_APPLICATION_CREDENTIALS="/path/to/keyfile.json"
